// Generated by gencpp from file inmoov_urdf/JointAngles.msg
// DO NOT EDIT!


#ifndef INMOOV_URDF_MESSAGE_JOINTANGLES_H
#define INMOOV_URDF_MESSAGE_JOINTANGLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace inmoov_urdf
{
template <class ContainerAllocator>
struct JointAngles_
{
  typedef JointAngles_<ContainerAllocator> Type;

  JointAngles_()
    : angles()  {
    }
  JointAngles_(const ContainerAllocator& _alloc)
    : angles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _angles_type;
  _angles_type angles;




  typedef boost::shared_ptr< ::inmoov_urdf::JointAngles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inmoov_urdf::JointAngles_<ContainerAllocator> const> ConstPtr;

}; // struct JointAngles_

typedef ::inmoov_urdf::JointAngles_<std::allocator<void> > JointAngles;

typedef boost::shared_ptr< ::inmoov_urdf::JointAngles > JointAnglesPtr;
typedef boost::shared_ptr< ::inmoov_urdf::JointAngles const> JointAnglesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inmoov_urdf::JointAngles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inmoov_urdf::JointAngles_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace inmoov_urdf

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'inmoov_urdf': ['/home/georgehartt/inmoov_ws/src/inmoov_urdf/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::inmoov_urdf::JointAngles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inmoov_urdf::JointAngles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inmoov_urdf::JointAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inmoov_urdf::JointAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inmoov_urdf::JointAngles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inmoov_urdf::JointAngles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inmoov_urdf::JointAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95f3b8363c7841811c5d5c57f880940e";
  }

  static const char* value(const ::inmoov_urdf::JointAngles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95f3b8363c784181ULL;
  static const uint64_t static_value2 = 0x1c5d5c57f880940eULL;
};

template<class ContainerAllocator>
struct DataType< ::inmoov_urdf::JointAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inmoov_urdf/JointAngles";
  }

  static const char* value(const ::inmoov_urdf::JointAngles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inmoov_urdf::JointAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16[] angles \n\
";
  }

  static const char* value(const ::inmoov_urdf::JointAngles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inmoov_urdf::JointAngles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointAngles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inmoov_urdf::JointAngles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inmoov_urdf::JointAngles_<ContainerAllocator>& v)
  {
    s << indent << "angles[]" << std::endl;
    for (size_t i = 0; i < v.angles.size(); ++i)
    {
      s << indent << "  angles[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.angles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // INMOOV_URDF_MESSAGE_JOINTANGLES_H
